### Packages

In [2]:
#pip install mplsoccer

In [3]:
import matplotlib.pyplot as plt
import numpy as np
from mplsoccer import Sbopen, Pitch, VerticalPitch

### Event data documentation

https://mplsoccer.readthedocs.io/en/latest/gallery/statsbomb/plot_statsbomb_data.html#event-data

In [5]:
parser = Sbopen()

# Load dataframes containing event data from a specific match. 'df_event' stores the main events, and the other dfs provide context for them.
df_event, df_related, df_freeze, df_tactics = parser.event(7478)

print(f"\ndf_event: {df_event.columns}")
print(f"\ndf_related: {df_related.columns}")
print(f"\ndf_freeze: {df_freeze.columns}")
print(f"\ndf_tactics: {df_tactics.columns}")

df_event: Index(['id', 'index', 'period', 'timestamp', 'minute', 'second', 'possession',
       'duration', 'match_id', 'type_id', 'type_name', 'possession_team_id',
       'possession_team_name', 'play_pattern_id', 'play_pattern_name',
       'team_id', 'team_name', 'tactics_formation', 'player_id', 'player_name',
       'position_id', 'position_name', 'pass_recipient_id',
       'pass_recipient_name', 'pass_length', 'pass_angle', 'pass_height_id',
       'pass_height_name', 'end_x', 'end_y', 'sub_type_id', 'sub_type_name',
       'body_part_id', 'body_part_name', 'x', 'y', 'under_pressure',
       'pass_switch', 'outcome_id', 'outcome_name',
       'ball_recovery_recovery_failure', 'counterpress', 'foul_won_defensive',
       'aerial_won', 'block_offensive', 'shot_statsbomb_xg', 'end_z',
       'technique_id', 'technique_name', 'goalkeeper_position_id',
       'goalkeeper_position_name', 'pass_assisted_shot_id', 'pass_goal_assist',
       'shot_key_pass_id', 'pass_cross', 'pass_backheel', 'dribble_overrun',
       'dribble_nutmeg', 'pass_shot_assist', 'shot_one_on_one',
       'foul_committed_penalty', 'foul_won_penalty', 'foul_committed_card_id',
       'foul_committed_card_name', 'foul_committed_offensive',
       'substitution_replacement_id', 'substitution_replacement_name',
       'ball_recovery_offensive', 'bad_behaviour_card_id',
       'bad_behaviour_card_name'],
      dtype='object')

df_related: Index(['match_id', 'id', 'index', 'type_name', 'id_related', 'index_related',
       'type_name_related'],
      dtype='object')

df_freeze: Index(['teammate', 'match_id', 'id', 'x', 'y', 'player_id', 'player_name',
       'position_id', 'position_name', 'event_freeze_id'],
      dtype='object')

df_tactics: Index(['jersey_number', 'match_id', 'id', 'player_id', 'player_name',
       'position_id', 'position_name', 'event_tactics_id'],
      dtype='object')

### Finding match data for Euro 2024

In [7]:
# Filter by competition
df_comp = parser.competition()
print(df_comp['competition_name'].unique())

mens_euros = df_comp[df_comp['competition_name']=="UEFA Euro"]
display(mens_euros)

# Find latest edition
print(f"Latest UEFA Euro with data available: {mens_euros['season_name'].max()}")

['1. Bundesliga' 'African Cup of Nations' 'Champions League'
 'Copa America' 'Copa del Rey' "FA Women's Super League"
 'FIFA U20 World Cup' 'FIFA World Cup' 'Frauen Bundesliga'
 'Indian Super league' 'La Liga' 'Liga F' 'Liga Profesional' 'Ligue 1'
 'Major League Soccer' 'North American League' 'NWSL' 'Premier League'
 'Serie A' 'Serie A Women' 'UEFA Euro' 'UEFA Europa League'
 "UEFA Women's Euro" "Women's World Cup"]

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
73,55,282,Europe,UEFA Euro,male,False,True,2024,2026-05-01T19:54:25.846072,2026-05-01T19:58:06.077979,2026-05-01T19:58:06.077979,2026-05-01T19:54:25.846072
74,55,43,Europe,UEFA Euro,male,False,True,2020,2026-05-10T12:59:26.302088,2026-05-10T13:00:25.564993,2026-05-10T13:00:25.564993,2026-05-10T12:59:26.302088

Latest UEFA Euro with data available: 2024

In [8]:
# Use competition_id and season_id to filter for match data

euros_2024 = parser.match(competition_id=55, season_id=282)
euros_2024.head()

,match_id,match_date,kick_off,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,match_week,...,competition_stage_id,competition_stage_name,stadium_id,stadium_name,stadium_country_id,stadium_country_name,referee_id,referee_name,referee_country_id,referee_country_name
0,3930166,2024-06-18,2024-06-18 19:00:00,2,1,available,available,2026-05-01 19:52:36.631184,2026-05-01 19:56:35.877702,1,...,10,Group Stage,376,Red Bull Arena,85,Germany,261,Marco Guida,112,Italy
1,3930159,2024-06-15,2024-06-15 13:00:00,1,3,available,available,2026-05-01 19:45:59.392947,2026-05-01 19:50:52.970161,1,...,10,Group Stage,363,RheinEnergieStadion,85,Germany,943,Slavko Vinčić,208,Slovenia
2,3930163,2024-06-16,2024-06-16 19:00:00,0,1,available,available,2026-05-01 19:48:19.783129,2026-05-01 19:49:47.226912,1,...,10,Group Stage,370,VELTINS-Arena,85,Germany,269,Daniele Orsato,112,Italy
3,3930181,2024-06-25,2024-06-25 19:00:00,0,0,available,available,2026-05-01 19:48:27.887397,2026-05-01 19:50:03.279607,3,...,10,Group Stage,363,RheinEnergieStadion,85,Germany,76,Clément Turpin,78,France
4,3930178,2024-06-24,2024-06-24 19:00:00,1,1,available,available,2026-05-01 19:45:23.956799,2026-05-01 19:46:35.413328,3,...,10,Group Stage,376,Red Bull Arena,85,Germany,293,Danny Desmond Makkelie,160,Netherlands

In [692]:
#help(Sbopen())
#euros_2024.columns
#euros_2024['home_team_name'].unique()

## Define the winger comparison group

In [208]:
# Example for Spain vs Croatia

import pandas as pd

game_1_right_wing = df_tactics_spain_1[df_tactics_spain_1['position_name']=='Right Wing']
game_1_left_wing = df_tactics_spain_1[df_tactics_spain_1['position_name']=='Left Wing']

#display(game_1_right_wing)
#display(game_1_left_wing)

wingers_spa_cro = pd.concat([game_1_right_wing, game_1_left_wing], axis=0)
wingers_spa_cro = wingers_spa_cro[['player_name', 'position_name']]

wingers_spa_cro.head(20)

                    player_name position_name
7   Lamine Yamal Nasraoui Ebana    Right Wing
19                  Lovro Majer    Right Wing
30                  Lovro Majer    Right Wing
41                Mario Pašalić    Right Wing
51  Lamine Yamal Nasraoui Ebana    Right Wing
9     Nicholas Williams Arthuer     Left Wing
20              Andrej Kramarić     Left Wing
31                 Ivan Perišić     Left Wing
42                 Ivan Perišić     Left Wing
53         Daniel Olmo Carvajal     Left Wing

### Get event data for all matches in the whole tournament

#### Try to do it using dicts? (adds more detail because each match is uniquely identified by match_id)

In [186]:
# All wingers in the whole tournament

match_ids = euros_2024['match_id']
all_matches = []

for match_id in match_ids:
    df_event, df_related, df_freeze, df_tactics = parser.event(match_id)
    all_matches.append(df_event)

all_matches

[                                        id  index  period        timestamp  \
 0     9d27853c-ffbc-4011-b7eb-fe3d438e8376      1       1         00:00:00
 1     39ad76b2-caaa-41e0-8eb5-f42de9e4e2c6      2       1         00:00:00
 2     4785617c-2983-4911-a9a6-9edd69fd948b      3       1         00:00:00
 3     4046659a-2a5c-496a-93a7-21c139e9fb8f      4       1         00:00:00
 4     87a790b7-17a6-4bbd-953f-a06c07edbad9      5       1  00:00:00.900000
 ...                                    ...    ...     ...              ...
 3605  beeeb493-804b-4ef5-bb2f-ffa6c2e17c65   3606       2  00:49:48.286000
 3606  8b1ad8bf-6817-40c7-847f-3a155b3d859f   3607       2  00:49:48.286000
 3607  ae7db9fa-f76f-49b6-8bdd-009ec98a5825   3608       2  00:49:59.374000
 3608  6cee3ae2-438e-4744-85a2-20bcc389bf8e   3609       2  00:50:02.891000
 3609  dc16247d-9803-4dcb-9b20-1cdbdb680557   3610       2  00:50:02.891000

       minute  second  possession   duration  match_id  type_id  ...  \
 0          0       0           1   0.000000   3930166       35  ...
 1          0       0           1   0.000000   3930166       35  ...
 2          0       0           1   0.000000   3930166       18  ...
 3          0       0           1   0.000000   3930166       18  ...
 4          0       0           2   1.536085   3930166       30  ...
 ...      ...     ...         ...        ...       ...      ...  ...
 3605      94      48         152   0.000000   3930166        2  ...
 3606      94      48         152  11.088229   3930166       43  ...
 3607      94      59         152   2.233897   3930166       30  ...
 3608      95       2         152   0.000000   3930166       34  ...
 3609      95       2         152   0.000000   3930166       34  ...

      foul_committed_card_name  foul_committed_advantage foul_won_advantage  \
 0                         NaN                       NaN                NaN
 1                         NaN                       NaN                NaN
 2                         NaN                       NaN                NaN
 3                         NaN                       NaN                NaN
 4                         NaN                       NaN                NaN
 ...                       ...                       ...                ...
 3605                      NaN                       NaN                NaN
 3606                      NaN                       NaN                NaN
 3607                      NaN                       NaN                NaN
 3608                      NaN                       NaN                NaN
 3609                      NaN                       NaN                NaN

       injury_stoppage_in_chain substitution_replacement_id  \
 0                          NaN                         NaN
 1                          NaN                         NaN
 2                          NaN                         NaN
 3                          NaN                         NaN
 4                          NaN                         NaN
 ...                        ...                         ...
 3605                       NaN                         NaN
 3606                       NaN                         NaN
 3607                       NaN                         NaN
 3608                       NaN                         NaN
 3609                       NaN                         NaN

       substitution_replacement_name pass_goal_assist foul_won_defensive  \
 0                               NaN              NaN                NaN
 1                               NaN              NaN                NaN
 2                               NaN              NaN                NaN
 3                               NaN              NaN                NaN
 4                               NaN              NaN                NaN
 ...                             ...              ...                ...
 3605                            NaN              NaN                NaN
 3606                            NaN              NaN                NaN
 3607                            NaN              NaN                NaN
 3608                            NaN              NaN                NaN
 3609                            NaN              NaN                NaN

       bad_behaviour_card_id bad_behaviour_card_name
 0                       NaN                     NaN
 1                       NaN                     NaN
 2                       NaN                     NaN
 3                       NaN                     NaN
 4                       NaN                     NaN
 ...                     ...                     ...
 3605                    NaN                     NaN
 3606                    NaN                     NaN
 3607                    NaN                     NaN
 3608                    NaN                     NaN
 3609                    NaN                     NaN

 [3610 rows x 72 columns],
                                         id  index  period        timestamp  \
 0     7d868ed2-93b2-4ea9-b759-bb627d88223a      1       1         00:00:00
 1     82792f80-3662-4c11-8e6c-7716a4409c3e      2       1         00:00:00
 2     5996805c-bf2a-4699-9fae-2bd62899dcb9      3       1         00:00:00
 3     388d095c-3d30-40dd-abe2-3b350227439a      4       1         00:00:00
 4     8ad85d85-b3b4-4da8-b338-440280c86265      5       1  00:00:00.310000
 ...                                    ...    ...     ...              ...
 3365  c49b5dc9-9836-4390-8dc3-19e781d983b2   3366       2  00:51:56.486000
 3366  24570825-23e0-4c7b-9e55-586fe7e0704c   3367       2  00:51:57.708000
 3367  0e86f9b1-2864-4810-bf96-b29d3a520a7d   3368       2  00:51:58.390000
 3368  0a2105ba-2782-4ff8-8f29-05f7e114a4a1   3369       2  00:52:00.570000
 3369  89dc76fb-fc57-4cde-afea-fd15bea5b633   3370       2  00:52:00.570000

       minute  second  possession  duration  match_id  type_id  ...  \
 0          0       0           1  0.000000   3930159       35  ...
 1          0       0           1  0.000000   3930159       35  ...
 2          0       0           1  0.000000   3930159       18  ...
 3          0       0           1  0.000000   3930159       18  ...
 4          0       0           2  1.685987   3930159       30  ...
 ...      ...     ...         ...       ...       ...      ...  ...
 3365      96      56         156  1.904318   3930159       43  ...
 3366      96      57         156  0.930616   3930159       17  ...
 3367      96      58         156  2.337491   3930159       30  ...
 3368      97       0         156  0.000000   3930159       34  ...
 3369      97       0         156  0.000000   3930159       34  ...

      foul_won_advantage  substitution_replacement_id  \
 0                   NaN                          NaN
 1                   NaN                          NaN
 2                   NaN                          NaN
 3                   NaN                          NaN
 4                   NaN                          NaN
 ...                 ...                          ...
 3365                NaN                          NaN
 3366                NaN                          NaN
 3367                NaN                          NaN
 3368                NaN                          NaN
 3369                NaN                          NaN

      substitution_replacement_name  pass_cut_back dribble_no_touch  \
 0                              NaN            NaN              NaN
 1                              NaN            NaN              NaN
 2                              NaN            NaN              NaN
 3                              NaN            NaN              NaN
 4                              NaN            NaN              NaN
 ...                            ...            ...              ...
 3365                           NaN            NaN              NaN
 3366                           NaN            NaN              NaN
 3367                           NaN            NaN              NaN
 3368                           NaN            NaN              NaN
 3369                           NaN            NaN              NaN

       dribble_overrun foul_committed_offensive ball_recovery_offensive  \
 0                 NaN                      NaN                     NaN
 1                 NaN                      NaN                     NaN
 2                 NaN                      NaN                     NaN
 3                 NaN                      NaN                     NaN
 4                 NaN                      NaN                     NaN
 ...               ...                      ...                     ...
 3365              NaN                      NaN                     NaN
 3366              NaN                      NaN                     NaN
 3367              NaN                      NaN                     NaN
 3368              NaN                      NaN                     NaN
 3369              NaN                      NaN                     NaN

       shot_deflected block_deflection
 0                NaN              NaN
 1                NaN              NaN
 2                NaN              NaN
 3                NaN              NaN
 4                NaN              NaN
 ...              ...              ...
 3365             NaN              NaN
 3366             NaN              NaN
 3367             NaN              NaN
 3368             NaN              NaN
 3369             NaN              NaN

 [3370 rows x 74 columns],
                                         id  index  period        timestamp  \
 0     8c3f0e43-76d2-43f6-b4df-e6fccb071996      1       1         00:00:00
 1     7c399a9f-b672-4f10-aa61-11e4ae633443      2       1         00:00:00
 2     e960f753-c383-4584-87a2-711faf49cd3a      3       1         00:00:00
 3     38387f30-0d78-40a8-915a-d434eb16063d      4       1         00:00:00
 4     10983cdd-eac3-4a13-82fb-eeaed6f07c02      5       1  00:00:00.458000
 ...                                    ...    ...     ...              ...
 3915  bb5b250d-f75d-416e-9b5e-6069aee44d69   3916       2  00:49:00.676000
 3916  acd1042b-ae87-4afa-b93f-8582cd07ddd4   3917       2  00:49:01.094000
 3917  03c3c559-333c-4a5c-9b54-6f2a9878c753   3918       2  00:49:01.094000
 3918  52d20d05-3190-4baf-aa04-2eb0ec3bb35c   3919       2  00:49:02.961000
 3919  38649e37-0203-4361-b456-c850e12cc845   3920       2  00:49:02.961000

       minute  second  possession  duration  match_id  type_id  ...  \
 0          0       0           1  0.000000   3930163       35  ...
 1          0       0           1  0.000000   3930163       35  ...
 2          0       0           1  0.000000   3930163       18  ...
 3          0       0           1  0.000000   3930163       18  ...
 4          0       0           2  2.469956   3930163       30  ...
 ...      ...     ...         ...       ...       ...      ...  ...
 3915      94       0         135  0.653781   3930163       17  ...
 3916      94       1         135       NaN   3930163       42  ...
 3917      94       1         135  0.000000   3930163        9  ...
 3918      94       2         135  0.000000   3930163       34  ...
 3919      94       2         135  0.000000   3930163       34  ...

      foul_committed_card_name  substitution_replacement_id  \
 0                         NaN                          NaN
 1                         NaN                          NaN
 2                         NaN                          NaN
 3                         NaN                          NaN
 4                         NaN                          NaN
 ...                       ...                          ...
 3915                      NaN                          NaN
 3916                      NaN                          NaN
 3917                      NaN                          NaN
 3918                      NaN                          NaN
 3919                      NaN                          NaN

      substitution_replacement_name  pass_cut_back dribble_overrun  \
 0                              NaN            NaN             NaN
 1                              NaN            NaN             NaN
 2                              NaN            NaN             NaN
 3                              NaN            NaN             NaN
 4                              NaN            NaN             NaN
 ...                            ...            ...             ...
 3915                           NaN            NaN             NaN
 3916                           NaN            NaN             NaN
 3917                           NaN            NaN             NaN
 3918                           NaN            NaN             NaN
 3919                           NaN            NaN             NaN

       ball_recovery_offensive dribble_nutmeg pass_no_touch  shot_first_time  \
 0                         NaN            NaN           NaN              NaN
 1                         NaN            NaN           NaN              NaN
 2                         NaN            NaN           NaN              NaN
 3                         NaN            NaN           NaN              NaN
 4                         NaN            NaN           NaN              NaN
 ...                       ...            ...           ...              ...
 3915                      NaN            NaN           NaN              NaN
 3916                      NaN            NaN           NaN              NaN
 3917                      NaN            NaN           NaN              NaN
 3918                      NaN            NaN           NaN              NaN
 3919                      NaN            NaN           NaN              NaN

      pass_miscommunication
 0                      NaN
 1                      NaN
 2                      NaN
 3                      NaN
 4                      NaN
 ...                    ...
 3915                   NaN
 3916                   NaN
 3917                   NaN
 3918                   NaN
 3919                   NaN

 [3920 rows x 70 columns],
                                         id  index  period        timestamp  \
 0     c66b605e-21c2-4605-96a3-069a544f2abb      1       1         00:00:00
 1     2187c98c-254c-4537-bde8-10404bdc29b2      2       1         00:00:00
 2     d16eab81-85e6-43ae-971f-fa5489f2f30a      3       1         00:00:00
 3     65ed5126-150a-4edb-a62a-75bb6b70ba76      4       1         00:00:00
 4     5c629533-2c74-4aa8-993f-c42e3b052663      5       1  00:00:01.404000
 ...                                    ...    ...     ...              ...
 3683  ee55b586-7e07-4f14-8375-445ee576c414   3684       2  00:48:57.264000
 3684  0a294007-9707-4e7d-b8c3-0af40faa5673   3685       2  00:48:59.506000
 3685  4b215aa5-e801-440d-a08c-e882c29528b4   3686       2  00:49:00.006000
 3686  b2802704-2436-45ff-8865-a4418c9a6905   3687       2  00:49:02.725000
 3687  b23b7a67-3678-4908-87bf-8866b6f2bc5c   3688       2  00:49:02.725000

       minute  second  possession  duration  match_id  type_id  ...  \
 0          0       0           1  0.000000   3930181       35  ...
 1          0       0           1  0.000000   3930181       35  ...
 2          0       0           1  0.000000   3930181       18  ...
 3          0       0           1  0.000000   3930181       18  ...
 4          0       1           2  2.477005   3930181       30  ...
 ...      ...     ...         ...       ...       ...      ...  ...
 3683      93      57         138  0.000000   3930181        9  ...
 3684      93      59         138  0.541335   3930181       17  ...
 3685      94       0         138  1.573784   3930181       30  ...
 3686      94       2         138  0.000000   3930181       34  ...
 3687      94       2         138  0.000000   3930181       34  ...

      foul_won_advantage  foul_won_defensive block_offensive  shot_first_time  \
 0                   NaN                 NaN             NaN              NaN
 1                   NaN                 NaN             NaN              NaN
 2                   NaN                 NaN             NaN              NaN
 3                   NaN                 NaN             NaN              NaN
 4                   NaN                 NaN             NaN              NaN
 ...                 ...                 ...             ...              ...
 3683                NaN                 NaN             NaN              NaN
 3684                NaN                 NaN             NaN              NaN
 3685                NaN                 NaN             NaN              NaN
 3686                NaN                 NaN             NaN              NaN
 3687                NaN                 NaN             NaN              NaN

      substitution_replacement_id  substitution_replacement_name  \
 0                            NaN                            NaN
 1                            NaN                            NaN
 2                            NaN                            NaN
 3                            NaN                            NaN
 4                            NaN                            NaN
 ...                          ...                            ...
 3683                         NaN                            NaN
 3684                         NaN                            NaN
 3685                         NaN                            NaN
 3686                         NaN                            NaN
 3687                         NaN                            NaN

      dribble_nutmeg bad_behaviour_card_id  bad_behaviour_card_name  \
 0               NaN                   NaN                      NaN
 1               NaN                   NaN                      NaN
 2               NaN                   NaN                      NaN
 3               NaN                   NaN                      NaN
 4               NaN                   NaN                      NaN
 ...             ...                   ...                      ...
 3683            NaN                   NaN                      NaN
 3684            NaN                   NaN                      NaN
 3685            NaN                   NaN                      NaN
 3686            NaN                   NaN                      NaN
 3687            NaN                   NaN                      NaN

      injury_stoppage_in_chain
 0                         NaN
 1                         NaN
 2                         NaN
 3                         NaN
 4                         NaN
 ...                       ...
 3683                      NaN
 3684                      NaN
 3685                      NaN
 3686                      NaN
 3687                      NaN

 [3688 rows x 72 columns],
                                         id  index  period        timestamp  \
 0     1eed041e-2760-4952-934b-bb5256e59271      1       1         00:00:00
 1     d4759bbf-dfdc-45b2-a2e9-86a0c237b529      2       1         00:00:00
 2     17a4a34b-5842-4c5b-9566-9f3d5d9715fb      3       1         00:00:00
 3     161f551d-be37-4f2f-923e-4ae5aa1237f9      4       1         00:00:00
 4     e517bc9a-e478-42b0-aa27-99c5b4d71d55      5       1  00:00:00.287000
 ...                                    ...    ...     ...              ...
 4003  14576e0e-8f0b-4978-9821-a591ac751e73   4004       2  00:52:21.306000
 4004  49321153-1db7-45c3-808e-b3c5fff5ed76   4005       2  00:52:22.217000
 4005  6072c170-5cb2-40e8-a62e-d9dbe09c5d0e   4006       2  00:53:59.520000
 4006  f164ef78-25cc-44ab-a48f-07d399212cc1   4007       2  00:54:01.182000
 4007  6c82ec56-7321-435b-877d-5785c4a3d5b5   4008       2  00:54:01.182000

       minute  second  possession  duration  match_id  type_id  ...  \
 0          0       0           1  0.000000   3930178       35  ...
 1          0       0           1  0.000000   3930178       35  ...
 2          0       0           1  0.000000   3930178       18  ...

In [213]:
all_matches_df = pd.concat(all_matches)
all_matches_df.head()

,id,index,period,timestamp,minute,second,possession,duration,match_id,type_id,...,shot_deflected,block_deflection,block_offensive,foul_committed_penalty,pass_deflected,shot_redirect,foul_won_penalty,shot_open_goal,block_save_block,shot_follows_dribble
0,9d27853c-ffbc-4011-b7eb-fe3d438e8376,1,1,00:00:00,0,0,1,0.000000,3930166,35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,39ad76b2-caaa-41e0-8eb5-f42de9e4e2c6,2,1,00:00:00,0,0,1,0.000000,3930166,35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4785617c-2983-4911-a9a6-9edd69fd948b,3,1,00:00:00,0,0,1,0.000000,3930166,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4046659a-2a5c-496a-93a7-21c139e9fb8f,4,1,00:00:00,0,0,1,0.000000,3930166,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,87a790b7-17a6-4bbd-953f-a06c07edbad9,5,1,00:00:00.900000,0,0,2,1.536085,3930166,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Most frequent position for each player (serves to legitimise the comparison of wingers; a defender/midfielder/striker might have been a winger for one game)

What I need:
- 'player_name' to identify each player
- 'position_name' to register the position
- .mode() to check most frequent position

In [382]:
most_freq_pos = all_matches_df.groupby('player_name')['position_name'].agg(lambda x: x.mode())
#print(most_freq_pos)

#most_freq_pos_df = most_freq_pos.to_frame().reset_index()
most_freq_pos_df['position_name'].value_counts()

position_name
Center Forward                                          47
Right Center Back                                       36
Left Center Back                                        35
Left Defensive Midfield                                 32
Right Wing                                              32
Right Defensive Midfield                                31
Left Wing                                               31
Goalkeeper                                              29
Left Back                                               27
Right Back                                              23
Center Attacking Midfield                               21
Left Wing Back                                          20
Right Wing Back                                         16
Left Center Midfield                                    14
Center Defensive Midfield                               13
Right Center Forward                                    13
Left Center Forward                                     12
Right Center Midfield                                   12
Center Back                                             12
Right Attacking Midfield                                10
Left Attacking Midfield                                  8
Left Midfield                                            8
Right Midfield                                           5
Substitute                                               5
[Center Attacking Midfield, Left Defensive Midfield]     1
[Left Center Back, Left Wing Back]                       1
[Center Attacking Midfield, Right Center Midfield]       1
Name: count, dtype: int64

In [423]:
wingers_df = most_freq_pos_df[most_freq_pos_df['position_name'].isin(['Left Wing', 'Right Wing','Left Midfield', 'Right Midfield'])]
wingers_df

I have wingers_df, which stores 76 rows (players with their most frequent position) with 2 columns (player_name and position_name).
all_events_df stores all events for all games in the tournmanet.

I need to take all_events_df and filter to only have winger and wide mifielder events (not other positions)? SO, I check for cases where the

                player_name   position_name
18          Andrea Cambiaso      Right Wing
21          Andreas Weimann      Right Wing
24          Andrej Kramarić       Left Wing
28        Andriy Yarmolenko  Right Midfield
32           Anthony Gordon       Left Wing
..                      ...             ...
449  Valentin Mihai Mihăilă   Left Midfield
454        Viktor Tsygankov      Right Wing
478             Yunus Akgün      Right Wing
483     Zuriko Davitashvili      Right Wing
490           Ľubomír Tupta       Left Wing

[76 rows x 2 columns]

### Filter to only include event actions by wingers and wide midfielders

In [483]:
# all_matches_df stores all events in a DataFrame

winger_events = all_matches_df[all_matches_df['position_name'].isin(wingers_df['position_name'])]
display(winger_events.head())
print(winger_events['player_name'].unique())

,id,index,period,timestamp,minute,second,possession,duration,match_id,type_id,...,shot_deflected,block_deflection,block_offensive,foul_committed_penalty,pass_deflected,shot_redirect,foul_won_penalty,shot_open_goal,block_save_block,shot_follows_dribble
3558,f6b16fab-cb7a-431c-b8c8-bb281fbc2b58,3559,2,00:48:00.016000,93,0,149,NaN,3930166,42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3559,9e217ee3-448e-46e2-b2d8-d9e135b4a73d,3560,2,00:48:00.016000,93,0,149,0.000000,3930166,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3566,7ee3b49c-ff7d-4f2a-aa98-df5086157299,3567,2,00:48:04.798000,93,4,149,1.514536,3930166,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3571,c8024b49-7567-40c2-a8a0-3c1add323b3e,3572,2,00:48:07.697000,93,7,149,NaN,3930166,42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3572,5c3b4c51-17ae-46f1-ba25-08ef3135d3ec,3573,2,00:48:07.697000,93,7,149,1.252091,3930166,43,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

['Petr Ševčík' 'Ondřej Lingr' 'Bukayo Saka' 'Phil Foden' 'Jarrod Bowen'
 'Petar Stojanović' 'Jan Mlakar' 'Cole Palmer' 'Jon Gorenc Stankovič'
 'Anthony Gordon' 'Luka Sučić' 'Mario Pašalić' 'Andrej Kramarić'
 'Ivan Perišić' 'Nicholas Williams Arthuer' 'Lamine Yamal Nasraoui Ebana'
 'Lovro Majer' 'Daniel Olmo Carvajal' 'Ferrán Torres García' 'Timi Elšnik'
 'Benjamin Verbič' 'Bradley Barcola' 'Ousmane Dembélé'
 'Kylian Mbappé Lottin' 'Randal Kolo Muani' 'Christoph Baumgartner'
 'Marcel Sabitzer' 'Konrad Laimer' 'Patrick Wimmer' 'Nicola Zalewski'
 'Kamil Grosicki' 'Romano Schmid' 'Zuriko Davitashvili'
 'Khvicha Kvaratskhelia' 'Giorgi Chakvetadze' 'Saba Lobzhanidze'
 'Arda Güler' 'Kenan Yildiz' 'Barış Alper Yılmaz'
 'Muhammed Kerem Aktürkoğlu' 'Florinel Teodor Coman' 'Viktor Tsygankov'
 'Dennis Man' 'Mykhailo Mudryk' 'Valentin Mihai Mihăilă'
 'Andriy Yarmolenko' 'Ianis Hagi' 'Lukáš Haraslín' 'Ivan Schranz'
 'Tomáš Suslov' 'Oleksandr Zubkov' 'Leo Sauer' 'Georgiy Sudakov'
 'Cody Mathès Gakpo' 'Xavi Simons' 'Donyell Malen' 'Jeremie Frimpong'
 'Jeremy Doku' 'Antoine Griezmann' 'Yannick Ferreira Carrasco'
 'Kevin De Bruyne' 'Bernardo Mota Veiga de Carvalho e Silva' 'Yunus Akgün'
 'Rafael Alexandre Conceição Leão' 'Pedro Lomba Neto' 'Žan Celar'
 'Florian Wirtz' 'Jamal Musiala' 'Leroy Sané' 'Maximilian Beier'
 'Ruben Vargas' 'Dan Ndoye' 'Fabian Rieder' 'Mohamed Zeki Amdouni'
 'Jude Bellingham' 'Martín Zubimendi Ibáñez' 'Mikel Merino Zazón'
 'Steven Bergwijn' 'Francisco Fernandes Conceição' 'João Félix Sequeira'
 'Andreas Weimann' 'Christian Dannemann Eriksen' 'Jonas Older Wind'
 'Mikkel Damsgaard' 'Eberechi Eze' 'Andreas Skov Olsen' 'Leandro Trossard'
 'Johan Bakayoko' 'Denis Alibec' 'Memphis Depay'
 'Diogo José Teixeira da Silva' 'Josip Iličić' 'Matúš Bero'
 'Ľubomír Tupta' 'Lazar Samardžić' 'Saša Lukić' 'Dušan Tadić' 'Luka Jović'
 'Nedim Bajrami' 'Jasir Asani' 'Mikel Oyarzabal Ugarte'
 'Fermin Lopez Marin' 'Arbër Hoxha' 'Ernest Muçi'
 'Alejandro Baena Rodríguez' 'Jacob Bruun Larsen' 'Kai Havertz'
 'Stephan El Shaarawy' 'Federico Chiesa' 'Mattia Zaccagni' 'Adrien Rabiot'
 'Denzel Dumfries' 'Kingsley Coman' 'Lorenzo Pellegrini' 'Andrea Cambiaso'
 'Ayoze Pérez Gutiérrez' 'Taulant Sulejmanov' 'Martin Baturina'
 'Chris Führich' 'Marcus Thuram' 'Dávid Ďuriš' 'Qazim Laçi'
 'Nicolò Barella' 'Michael Ijemuan Folorunsho' 'Deian Cristian Sorescu'
 'Dodi Lukebakio' 'Ryan Christie' 'John McGinn' 'Thomas Müller']

In [485]:
winger_events['type_name'].value_counts()

type_name
Ball Receipt        6468
Carry               5355
Pass                5122
Pressure            2248
Ball Recovery        585
Dribble              449
Duel                 369
Shot                 305
Dispossessed         266
Block                250
Foul Won             238
Miscontrol           237
Foul Committed       168
Dribbled Past        111
Substitution         109
Clearance             86
Interception          78
50/50                 60
Injury Stoppage       25
Shield                14
Player On             13
Player Off            13
Bad Behaviour          5
Offside                4
Error                  2
Own Goal Against       1
Name: count, dtype: int64

## Calculating successful dribbles in the final third of the pitch

In [636]:
all_dribbles = (winger_events[winger_events['type_name'] == 'Dribble'])
#all_dribbles['outcome_name'].unique()

completed_dribbles = all_dribbles[all_dribbles['outcome_name']=='Complete']
final_third_completed_dribbles = completed_dribbles[completed_dribbles['x'] >= 80]
#final_third_completed_dribbles.head()

In [628]:
final_third_completed_dribbles_ranking = (
    final_third_completed_dribbles
    .groupby('player_name')
    .size()
    .reset_index(name='dribbles')
    .sort_values(by='dribbles',ascending=False)
)

final_third_completed_dribbles_ranking.head(25)

                        player_name  dribbles
33        Nicholas Williams Arthuer        11
24      Lamine Yamal Nasraoui Ebana        10
8                 Cody Mathès Gakpo         8
34                  Ousmane Dembélé         8
12                    Donyell Malen         7
19                      Jeremy Doku         7
0                   Andrej Kramarić         6
13                  Federico Chiesa         5
14                    Florian Wirtz         5
17                    Jamal Musiala         5
5                       Bukayo Saka         5
3                Barış Alper Yılmaz         4
23             Kylian Mbappé Lottin         4
31        Muhammed Kerem Aktürkoğlu         4
21                     Kenan Yildiz         4
37  Rafael Alexandre Conceição Leão         4
32                  Mykhailo Mudryk         4
15    Francisco Fernandes Conceição         4
11                       Dennis Man         3
10             Daniel Olmo Carvajal         3
22            Khvicha Kvaratskhelia         3
36                       Phil Foden         3
27                   Lukáš Haraslín         3
26                       Leroy Sané         3
35                 Petar Stojanović         2

In [662]:
final_third_dribbles_ranking

                        player_name  dribbles
51        Nicholas Williams Arthuer        24
36      Lamine Yamal Nasraoui Ebana        18
52                  Ousmane Dembélé        15
57  Rafael Alexandre Conceição Leão        12
26                    Jamal Musiala        10
..                              ...       ...
19                     Eberechi Eze         1
24                     Ivan Perišić         1
13                        Dan Ndoye         1
50                    Nedim Bajrami         1
0                     Adrien Rabiot         1

[67 rows x 2 columns]

## Calculating successful dribble rate in the final third of the pitch

- Successful Dribble Rate = Successful Dribbles / All Dribbles

In [686]:
final_third_dribbles = all_dribbles[all_dribbles['x'] >= 80]

final_third_dribbles_ranking = (
    final_third_dribbles
    .groupby('player_name')
    .size()
    .reset_index(name='dribbles')
    .sort_values(by='dribbles',ascending=False)
)

final_third_rates = final_third_dribbles_ranking.merge(
    final_third_completed_dribbles_ranking,
    on='player_name',
    suffixes=('_attempts', '_completed')
)

final_third_rates = final_third_rates[final_third_rates['dribbles_attempts']>=5]
final_third_rates['dribbles_completed'] = final_third_rates['dribbles_completed'].fillna(0)
final_third_rates['success_rate'] = final_third_rates['dribbles_completed'] / final_third_rates['dribbles_attempts']
final_third_rates = final_third_rates.sort_values(by='success_rate', ascending=False).set_index('player_name')

display(final_third_rates)

,dribbles_attempts,dribbles_completed,success_rate
player_name,,,
Cody Mathès Gakpo,8,8,1.000000
Donyell Malen,8,7,0.875000
Andrej Kramarić,7,6,0.857143
Federico Chiesa,6,5,0.833333
Barış Alper Yılmaz,5,4,0.800000
Muhammed Kerem Aktürkoğlu,5,4,0.800000
Jeremy Doku,10,7,0.700000
Daniel Olmo Carvajal,5,3,0.600000
Francisco Fernandes Conceição,7,4,0.571429
Bukayo Saka,9,5,0.555556
Lamine Yamal Nasraoui Ebana,18,10,0.555556
Florian Wirtz,9,5,0.555556
Ousmane Dembélé,15,8,0.533333
Jamal Musiala,10,5,0.500000
Kenan Yildiz,8,4,0.500000
Kylian Mbappé Lottin,8,4,0.500000
Nicholas Williams Arthuer,24,11,0.458333
Khvicha Kvaratskhelia,7,3,0.428571
Petar Stojanović,5,2,0.400000
Leroy Sané,8,3,0.375000
Dennis Man,8,3,0.375000
Rafael Alexandre Conceição Leão,12,4,0.333333

## Nico Williams Analysis

In [ ]:
spain_home_match_ids = euros_2024[euros_2024['home_team_name']=='Spain'].match_id
spain_away_match_ids = euros_2024[euros_2024['away_team_name']=='Spain'].match_id

print(f"Spain home match(es) id(s):\n{spain_home_match_ids.to_string(index=False)}")
print(f"\nSpain away match(es) id(s): {spain_away_match_ids.to_string(index=False)}")
print(f"\nNumber of games played by Spain: {len(spain_home_match_ids) + len(spain_away_match_ids)}")

In [ ]:
# Loading games
df_event_spain_1, df_related_spain_1, df_freeze_spain_1, df_tactics_spain_1 = parser.event(3930160)
df_event_spain_2, df_related_spain_2, df_freeze_spain_2, df_tactics_spain_2 = parser.event(3943043)

# Nico Williams did not play in this game
df_event_spain_3, df_related_spain_3, df_freeze_spain_3, df_tactics_spain_3 = parser.event(3930179)

df_event_spain_4, df_related_spain_4, df_freeze_spain_4, df_tactics_spain_4 = parser.event(3942752)
df_event_spain_5, df_related_spain_5, df_freeze_spain_5, df_tactics_spain_5 = parser.event(3942226)
df_event_spain_6, df_related_spain_6, df_freeze_spain_6, df_tactics_spain_6 = parser.event(3941018)
df_event_spain_7, df_related_spain_7, df_freeze_spain_7, df_tactics_spain_7 = parser.event(3930172)

In [ ]:
df_event_spain_1.columns